# Generated by Django 3.0.2 on 2020-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('apleId', models.IntegerField(verbose_name='apleId')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('collectionName', models.CharField(max_length=50, verbose_name='collectionName')),
                ('apleId', models.IntegerField(verbose_name='apleId')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('explicitness', models.IntegerField(blank=True, choices=[(0, 'Not Explicit'), (1, 'Explicit')], null=True, verbose_name='Explicitness')),
                ('discNumber', models.IntegerField(verbose_name='discNumber')),
                ('trackTimeMillis', models.IntegerField(verbose_name='trackTimeMillis')),
                ('artists', models.ManyToManyField(blank=True, to='core.Artist', verbose_name='Artists')),
                ('genres', models.ManyToManyField(blank=True, to='core.Genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, to='core.Genre', verbose_name='Genres'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('collectionName', models.CharField(max_length=50, verbose_name='collectionName')),
                ('apleId', models.IntegerField(verbose_name='apleId')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('explicitness', models.IntegerField(blank=True, choices=[(0, 'Not Explicit'), (1, 'Explicit')], null=True, verbose_name='Explicitness')),
                ('artists', models.ManyToManyField(blank=True, to='core.Artist', verbose_name='Artists')),
                ('genres', models.ManyToManyField(blank=True, to='core.Genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
