# Generated by Django 3.0.2 on 2020-01-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('collectionName', models.CharField(max_length=50, verbose_name='collectionName')),
                ('apleId', models.IntegerField(verbose_name='apleId')),
                ('artists', models.ManyToManyField(blank=True, to='core.Artist', verbose_name='Artists')),
                ('genres', models.ManyToManyField(blank=True, to='core.Genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
