from .genre_model_test_case import GenreModelTestCase
from .artist_model_test_case import ArtistModelTestCase
from .album_model_test_case import AlbumModelTestCase
from .music_model_test_case import MusicModelTestCase